In [1]:
import pandas as pd
import numpy as np
import mne
import os

import torch

In [2]:
from eeg_lib.commons.constant import DATASETS_FOLDER
from EEGDataExtractor import EEGDataExtractor

In [ ]:
DATA_DIR = f"{DATASETS_FOLDER}/Kolory/"

extractor = EEGDataExtractor(data_dir=DATA_DIR)
eeg_df, participants_info = extractor.extract_dataframe()

In [4]:
participants = eeg_df["participant_id"].unique()

In [5]:
eeg_df.head()

participant_id                                              epoch  label
0  011595b1@1651  [[1.5994905899983496e-06, 4.660259780289654e-0...   gray
1  011595b1@1651  [[3.2936710911247503e-06, 3.745427511069207e-0...  green
2  011595b1@1651  [[4.327731927482567e-06, 2.515285592381088e-06...   gray
3  011595b1@1651  [[1.7759480686267016e-06, -3.0099938072414544e...    red
4  011595b1@1651  [[4.0924612078715145e-06, 4.532130983695527e-0...   gray

In [6]:
for participant_id in participants:
    print(participant_id, ": ",len(eeg_df[eeg_df["participant_id"] == participant_id]))

011595b1@1651 :  232
022e8467@1910 :  232
06f240e9@1215 :  232
25d0bdb3@1318 :  232
2718372d@1400 :  232
2882ae26@1441 :  232
3033b74a@1626 :  232
36eea4bb@1519 :  232
39285860@1825 :  232
446b3735@1618 :  232
46607ce4@1717 :  232
51ec2c20@0923 :  232
541c91f2@1456 :  232
548fd734@1628 :  232
54e60118@1339 :  232
6d9a8b86@1613 :  232
6e542bc2@0845 :  232
8bd3032e@1746 :  232
8dca0725@1418 :  232
90441f44@1643 :  232
9e8bae0e@1828 :  232
b34b1427@0906 :  232
bf2d2193@1638 :  232
d87e1bd3@1806 :  232
e08138e2@1731 :  232
e283301e@1606 :  232
e43a9f9f@0941 :  232
f82b5699@1757 :  232
fd8a3308@1135 :  232
ffae50df@1712 :  232


In [7]:
eeg_df[eeg_df["participant_id"] == "011595b1@1651"].iloc[:3]["epoch"][0]

array([[ 1.59949059e-06,  4.66025978e-07, -2.15380011e-06, ...,
         1.29476315e-06,  8.50347724e-07,  1.66841336e-06],
       [ 1.61846220e-06,  1.19613053e-06,  1.29070086e-06, ...,
         3.26989160e-06,  2.71957984e-06,  2.37409640e-06],
       [-1.76377514e-05, -2.12479183e-05, -1.82417335e-05, ...,
         2.06641293e-05,  2.82200662e-05,  3.94110464e-05],
       [ 2.17844413e-05,  5.21727712e-06, -6.40627642e-06, ...,
         1.53385355e-05,  2.48763533e-05,  2.15969502e-05]])

In [8]:
epoch_arr = np.array(eeg_df["epoch"])

In [9]:
type(eeg_df["epoch"])

pandas.core.series.Series

In [10]:
eeg_df["epoch"][0]

array([[ 1.59949059e-06,  4.66025978e-07, -2.15380011e-06, ...,
         1.29476315e-06,  8.50347724e-07,  1.66841336e-06],
       [ 1.61846220e-06,  1.19613053e-06,  1.29070086e-06, ...,
         3.26989160e-06,  2.71957984e-06,  2.37409640e-06],
       [-1.76377514e-05, -2.12479183e-05, -1.82417335e-05, ...,
         2.06641293e-05,  2.82200662e-05,  3.94110464e-05],
       [ 2.17844413e-05,  5.21727712e-06, -6.40627642e-06, ...,
         1.53385355e-05,  2.48763533e-05,  2.15969502e-05]])

In [11]:
epoch_arr

array([array([[ 1.59949059e-06,  4.66025978e-07, -2.15380011e-06, ...,
                1.29476315e-06,  8.50347724e-07,  1.66841336e-06],
              [ 1.61846220e-06,  1.19613053e-06,  1.29070086e-06, ...,
                3.26989160e-06,  2.71957984e-06,  2.37409640e-06],
              [-1.76377514e-05, -2.12479183e-05, -1.82417335e-05, ...,
                2.06641293e-05,  2.82200662e-05,  3.94110464e-05],
              [ 2.17844413e-05,  5.21727712e-06, -6.40627642e-06, ...,
                1.53385355e-05,  2.48763533e-05,  2.15969502e-05]])   ,
       array([[ 3.29367109e-06,  3.74542751e-06,  5.06992830e-06, ...,
                3.50408986e-07,  2.80187099e-07,  1.58227828e-06],
              [ 2.73615077e-06,  2.00023892e-06,  1.42513194e-06, ...,
                4.24060812e-06,  4.00058582e-06,  3.56233503e-06],
              [ 4.61146433e-05,  5.11495619e-05,  5.27189231e-05, ...,
               -6.94740702e-06, -1.36208859e-05, -1.32924158e-05],
              [ 3.14694212e-0

In [12]:
user_id_dict = {}

In [13]:
for part_id in participants:
    user_id_dict[part_id] = eeg_df.index[eeg_df["participant_id"] == part_id].tolist()

In [14]:
user_id_dict['011595b1@1651']

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [15]:
eeg_df.iloc[250]

participant_id                                        022e8467@1910
epoch             [[2.213623469691974e-06, 2.6448830073688394e-0...
label                                                          gray
Name: 250, dtype: object

In [16]:
eeg_data = eeg_df["epoch"]

In [17]:
eeg_df["epoch"].iloc[250]

array([[ 2.21362347e-06,  2.64488301e-06,  3.39959845e-06, ...,
         3.95953234e-06,  3.85470778e-06,  4.23915650e-06],
       [ 1.39258077e-06,  4.16855907e-06,  5.88652117e-06, ...,
        -6.91203140e-06, -5.64681733e-06, -2.38535850e-06],
       [-8.10027939e-06, -1.23697641e-05, -9.27614911e-06, ...,
         3.65912691e-06,  2.52814218e-06, -3.52038209e-06],
       [-1.67271219e-05, -1.93314836e-05, -1.98509478e-05, ...,
         2.08944094e-06,  3.71639370e-06,  2.34445036e-06]])

In [18]:
import torch

In [19]:
a = torch.tensor(eeg_data[250])

In [20]:
a.shape

torch.Size([4, 751])

In [21]:
eeg_df.head()["epoch"][0].shape

(4, 751)

In [22]:
eeg_df.head()["epoch"][3]

array([[ 1.77594807e-06, -3.00999381e-07, -1.13858876e-07, ...,
         4.04488247e-06,  3.18468142e-06,  2.67001252e-06],
       [ 6.70116693e-07,  6.56563747e-07,  1.30749330e-06, ...,
        -5.86080876e-07, -6.12893828e-07,  3.66139542e-07],
       [-2.17900581e-05, -9.94779973e-06, -6.93595355e-06, ...,
        -1.91076917e-05, -1.23131892e-05, -1.97852490e-06],
       [ 3.13697207e-06, -2.62453285e-07,  9.06989390e-06, ...,
        -4.09788245e-06, -1.35619871e-06,  5.62695698e-06]])

In [23]:
eeg_df.head()

participant_id                                              epoch  label
0  011595b1@1651  [[1.5994905899983496e-06, 4.660259780289654e-0...   gray
1  011595b1@1651  [[3.2936710911247503e-06, 3.745427511069207e-0...  green
2  011595b1@1651  [[4.327731927482567e-06, 2.515285592381088e-06...   gray
3  011595b1@1651  [[1.7759480686267016e-06, -3.0099938072414544e...    red
4  011595b1@1651  [[4.0924612078715145e-06, 4.532130983695527e-0...   gray

In [24]:
eeg_df["epoch"][0].shape

(4, 751)

In [26]:
eeg_df.head()

participant_id  \
0  011595b1@1651   
1  011595b1@1651   
2  011595b1@1651   
3  011595b1@1651   
4  011595b1@1651   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         

In [27]:
eeg_df.iloc[4]["participant_id"]

'011595b1@1651'